Tests for deleting subjects, users and classes
t0r8ern1t/scheduleTestFramework pull request #6
Opened 2024-05-04 19:52 UTC by t0r8ern1t

2024-05-06 14:04 UTC, Tawoker requested changes
Тест-кейсы у себя запустил, всё работает, основные замечания к классу `ScheduleUser`.
В тест-кейсах много проверок, очень надёжные)

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/TestEntities/ScheduleUser.cs
> +        public ScheduleGroup? Group { get; set; }
`public List<ScheduleSubject>? Subjects { get; set; }
public ScheduleGroup? Group { get; set; }`
Данные свойства присущи не каждому юзеру. Мне кажется, лучше бы вынести юзеров в дочерние классы

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/TestEntities/ScheduleUser.cs
> +        public void MakeStudentUser(string id, ScheduleGroup group)
Методы выше: MakeAdminUser, MakeTeacherUser, и MakeStudentUser могли бы быть конструкторами соответствующих дочерних классов, а также могли бы вызывать конструктор базового класса, это бы помогло избежать дублирования кода

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/TestCases/Case_DeleteTeacher.cs
> +        public void DeleteTeacher(ScheduleHomePage homePage)
Не понятно зачем в этом тест-кейсе создаётся пара, когда сам тест-кейс о преподавателе. Надо либо переназвать тест-кейс, так чтобы было понятно что он проверяет, либо поменять его логику на соответствующую названию.
В кейсах DeleteSubject, DeleteClassroom, DeleteUser такого нет.

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/TestCases/Case_DeleteAdmin.cs
> +            ScheduleUser user = new ScheduleUser();
После этой строчки, по логике, должен вызываться MakeAdminUser(), хоть и по реализации это то же самое что и ScheduleUser().
Я расписал в коментах, в файле ScheduleUser.cs, что можно сделать с юзерами, для того чтобы избежать путаницы

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/TestCases/NotCase_CreateObjects.cs
> +    public class NotCase_CreateObjects
Этот класс можно сделать абстрактным, а его методы статическими, потому что экземпляры объектов этого класса не имеют смысла, как мне кажется.

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/TestCases/Case_DeleteClass.cs
> +            NotCase_CreateObjects sys = new NotCase_CreateObjects();
По названию переменной ничего не понятно, раз этот объект создаёт объекты расписания, то ему можно подобрать соответствующее название, например objectCreator

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/PageObjects/ScheduleHomePage.cs
> +            WebItem subject = new WebItem(cellXpath+$"//child::p[contains(text(), {myclass.Subject.Title})]", "Предмет пары по искомому номеру и дню недели");
Текст {myclass.Subject.Title} внутри contains должен быть обёрнут в кавычки, иначе он неправильно работает, то же самое ко всем остальным contains в методе IsClassPresent

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/PageObjects/ScheduleHomePage.cs
> +            WebItem subject = new WebItem(cellXpath+$"//child::p[contains(text(), {myclass.Subject.Title})]", "Предмет пары по искомому номеру и дню недели");
Неправильная работа заключается в том, что он не ищет этот текст, а выдаёт всё подряд 
![image](https://github.com/t0r8ern1t/scheduleTestFramework/assets/67479814/5206c421-7caa-42d1-9ac6-ca9b54b99647)

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/PageObjects/AdminPanel/Classrooms/ScheduleEditClassroomPage.cs
> +            new WebItem("//input[@name='TITLE']", "Поле ввода Название").SendKeys(editedClassroom.Title);
здесь локатор `"//input[@name='NUMBER']"`

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/PageObjects/ScheduleHomePage.cs
> +            WebItem subject = new WebItem(cellXpath+$"//child::p[contains(text(), {myclass.Subject.Title})]", "Предмет пары по искомому номеру и дню недели");
То есть `isPresent` всегда будет `true`

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/TestCases/Case_DeleteClassroom.cs
> +            ScheduleClassroom classroom = new ScheduleClassroom(("Room" + id).Substring(0, 9), type);
Тут надо обрезать не с левой части, т.к. она остается одинаковой между тест-кейсами. Попробуй обрезать конец, либо рандомное число генерировать.

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/TestCases/Case_DeleteClassroom.cs
> +            ScheduleClassroom classroom = new ScheduleClassroom(("Room" + id).Substring(0, 9), type);
![image](https://github.com/t0r8ern1t/scheduleTestFramework/assets/67479814/40ed72bb-ff4e-4257-94bb-62d731a001f0)

2024-05-06 14:04 UTC, Tawoker commented on ATlearning/ATframework3demo/TestCases/Case_DeleteClassroom.cs
> +            ScheduleClassroom classroom = new ScheduleClassroom(("Room" + id).Substring(0, 9), type);
Это результат после нескольких запусков тест-кейсов

2024-05-07 12:21 UTC, t0r8ern1t commented on ATlearning/ATframework3demo/TestEntities/ScheduleUser.cs
> +        public ScheduleGroup? Group { get; set; }
Исправила в коммите e640f91

2024-05-07 12:22 UTC, t0r8ern1t commented on ATlearning/ATframework3demo/TestCases/NotCase_CreateObjects.cs
> +    public class NotCase_CreateObjects
По фактам, исправила в e640f91

2024-05-07 12:23 UTC, t0r8ern1t commented on ATlearning/ATframework3demo/PageObjects/ScheduleHomePage.cs
> +            WebItem subject = new WebItem(cellXpath+$"//child::p[contains(text(), {myclass.Subject.Title})]", "Предмет пары по искомому номеру и дню недели");
При отсутствии пары isPresent все-таки false, но тут тоже исправила в e640f91

2024-05-07 12:24 UTC, t0r8ern1t commented on ATlearning/ATframework3demo/PageObjects/AdminPanel/Classrooms/ScheduleEditClassroomPage.cs
> +            new WebItem("//input[@name='TITLE']", "Поле ввода Название").SendKeys(editedClassroom.Title);
Тоже верно, исправила

2024-05-07 12:25 UTC, t0r8ern1t commented on ATlearning/ATframework3demo/TestCases/Case_DeleteClassroom.cs
> +            ScheduleClassroom classroom = new ScheduleClassroom(("Room" + id).Substring(0, 9), type);
Изменила на генерацию рандомного числа, да

2024-05-07 13:39 UTC, Tawoker approved these changes
Все замечания исправлены. Новых не имеется. Всё красиво оформлено)

2024-05-07 13:40 UTC, merged